import os
# The content generated by your Day 3 Prompt
raw_content = """### MEETING SNIPPETS (Files 001-020)

Date: 2026-08-18 10:00 AM | Attendees: Samuel Lee, Ben Richardson, David O’Sullivan | Source: Meeting Minute
**Snippet 001: Weekly Progress Review (Infrastructure)**
* Discussion: Ben reported that the Foundation Piling - North Sector (Task 13.0) is officially Blocked. Heavy seasonal monsoon rains have flooded the excavation pits. Work cannot resume until the pumps clear the site.
---FILE_BREAK---
Date: 2026-10-20 02:00 PM | Attendees: Marcus Wong, Daniel Kim, Robert Kwok | Source: Meeting Minute
**Snippet 002: Digital Command Centre Sync**
* Discussion: Daniel noted that the 5G Node Hardware install (Task 19.0) might be delayed. He suggested we start "whenever the North Sector is ready, maybe mid-November?"
---FILE_BREAK---
Date: 2026-12-08 11:30 AM | Attendees: Arjun Mehta, Priya Lakshmi, Zoe Castellano | Source: Meeting Minute
**Snippet 003: Urban Design Workshop**
* Discussion: Arjun requested a New Task: "Smart Wayfinding Totem Placement Study." This needs to be completed before the Interior Public Space Ergonomics (Task 24.0) begins.
---FILE_BREAK---
Date: 2026-05-19 09:00 AM | Attendees: David O’Sullivan, Sarah Chen, Hiroshi Tanaka | Source: Meeting Minute
**Snippet 004: Structural Integrity Briefing**
* Discussion: Regarding Task 6.0 (Bridge Piling Plan), David mentioned it should be wrapped up "sometime late next month."
---FILE_BREAK---
Date: 2026-06-16 04:00 PM | Attendees: Elena Rodriguez, Chloe Dupont, Fatima Zahra | Source: Meeting Minute
**Snippet 005: Sustainability Committee**
* Discussion: Elena confirmed a New Task: "Circular Economy Material Verification." This is an urgent requirement from the building council to maintain the project’s LEED Gold status.
---FILE_BREAK---
Date: 2026-08-10 10:00 AM | Attendees: James Peterson, Ben Richardson | Source: Meeting Minute
**Snippet 006: Site Safety Audit**
* Discussion: Foundation Piling (Task 13.0) is further Blocked. Site crews hit an unmapped 1950s water main. All drilling is suspended until the utility company can bypass the line.
---FILE_BREAK---
Date: 2026-05-05 02:00 PM | Attendees: Marcus Wong, Sarah Chen | Source: Meeting Minute
**Snippet 007: Tech Integration Sync**
* Discussion: Marcus proposed a New Task: "Cyber-Physical Stress Test." This must occur immediately before the Digital Twin Sync (Task 4.0) to ensure the 5G nodes can handle the data load.
---FILE_BREAK---
Date: 2026-07-14 09:30 AM | Attendees: Rachael Smythe, Samuel Lee | Source: Meeting Minute
**Snippet 008: Stakeholder Briefing**
* Discussion: The Public Stakeholder Town Hall (Task 11.0) has a confirmed date change. It is moved from July 13 to July 27 to accommodate the local council members' schedules.
---FILE_BREAK---
Date: 2026-06-09 11:00 AM | Attendees: Geoffery Tan, Jessica Low | Source: Meeting Minute
**Snippet 009: Legal & Risk Review**
* Discussion: Geoffery noted that the Heritage protection strategy (Task 8.0) needs to be finalized "ASAP, definitely before the end of the summer."
---FILE_BREAK---
Date: 2026-04-21 10:00 AM | Attendees: Chloe Dupont, Samuel Lee | Source: Meeting Minute
**Snippet 010: Environmental Oversight**
* Discussion: Chloe flagged a New Task: "Migratory Bird Flight Path Audit." Recent environmental surveys near the Nexus Bridge site indicate a protected species nesting nearby.
---FILE_BREAK---
Date: 2026-10-20 03:00 PM | Attendees: Amina Al-Farsi, Daniel Kim, Robert Kwok | Source: Meeting Minute
**Snippet 011: 5G Infrastructure & Connectivity Sync**
* Discussion: Daniel reported that the 5G Node Hardware Install (Task 19.0) is now Blocked. A global shortage of semi-conductor housing units has halted the assembly line.
---FILE_BREAK---
Date: 2026-11-03 01:00 PM | Attendees: Priya Lakshmi, Elena Rodriguez, Vikram Singh | Source: Meeting Minute
**Snippet 012: Sustainable Landscapes & Irrigation**
* Discussion: Priya introduced a New Task: "Greywater Filtration System Integration." This must be mapped into the hydraulic plan before Task 20.0 concludes.
---FILE_BREAK---
Date: 2026-09-22 09:00 AM | Attendees: Linda Ng, David O’Sullivan, Sarah Chen | Source: Meeting Minute
**Snippet 013: MEP & Structural Coordination**
* Discussion: A conflict arose regarding Task 17.0 (MEP Corridor Optimization). Linda claims she is leading the optimization, but David insists his structural team needs to own the heights.
---FILE_BREAK---
Date: 2026-05-12 11:00 AM | Attendees: Marcus Wong, Alice Thompson, Kevin Zhang | Source: Meeting Minute
**Snippet 014: Digital Twin Data Integration**
* Discussion: Marcus confirmed a date change for the Digital Twin Framework (Task 4.0). Due to GSIMS mapping delays, the new Start Date is set for May 18, 2026.
---FILE_BREAK---
Date: 2026-12-02 02:00 PM | Attendees: Arjun Mehta, Rachael Smythe | Source: Meeting Minute
**Snippet 015: Urban Nexus Masterplan Review**
* Discussion: Arjun requested a New Task: "Public Realm Shade Analysis" to simulate heat islands following feedback from the town hall.
---FILE_BREAK---
Date: 2026-06-02 03:00 PM | Attendees: Sofia Rossi, Ben Richardson | Source: Meeting Minute
**Snippet 016: Logistics & Procurement Briefing**
* Discussion: Sofia noted that the Structural Steel Procurement (Task 7.0) is still Blocked. Customs has flagged the alloy composition for additional testing.
---FILE_BREAK---
Date: 2026-08-25 10:00 AM | Attendees: Fatima Zahra, Samuel Lee | Source: Meeting Minute
**Snippet 017: Smart Grid & Energy Strategy**
* Discussion: Regarding the Smart Grid Integration (Task 14.0), Fatima mentioned the physical install will begin "probably sometime after the monsoon season clears up."
---FILE_BREAK---
Date: 2027-01-05 04:00 PM | Attendees: Robert Kwok, Daniel Kim | Source: Meeting Minute
**Snippet 018: Operational Technology (OT) Security**
* Discussion: Robert mandated a New Task: "Intrusion Detection System (IDS) Calibration." This must be performed on the 5G nodes before syncing to the GSIMS platform.
---FILE_BREAK---
Date: 2026-05-18 11:00 AM | Attendees: Hiroshi Tanaka, David O’Sullivan | Source: Meeting Minute
**Snippet 019: Geotechnical & Foundation Close-out**
* Discussion: Hiroshi updated the timeline for the Geotechnical Site Assessment (Task 2.0). Final report for the South Pier will now be delivered on May 29, 2026.
---FILE_BREAK---
Date: 2026-07-07 09:00 AM | Attendees: Emily Watson, Arjun Mehta, Sarah Chen | Source: Meeting Minute
**Snippet 020: Heritage & Conservation Oversight**
* Discussion: Conflict regarding Task 10.0 (BIM Coordination) for the heritage zone. Emily believes she should be the primary Owner, while Sarah insists all layers stay under her management.

### EMAIL THREADS (Files 021-050)

---FILE_BREAK---
Date: 2026-06-01 08:45 AM | Recipients: Sofia Rossi, Samuel Lee | Source: Email
From: Sofia Rossi | To: Samuel Lee | Subject: Supply Chain Update: Task 7.0
Samuel, the high-grade structural steel for the Nexus Bridge is held up at the port. Task 7.0 (Procurement) is Blocked. I anticipate a 4-week delay.
---FILE_BREAK---
Date: 2026-09-08 09:12 AM | Recipients: Samuel Lee, Sarah Chen, Alice Thompson | Source: Email
From: Samuel Lee | To: Sarah Chen, Alice Thompson | Subject: GSIMS Platform Oversight
Sarah, I’d like you to take the lead on the GSIMS Platform Spatial Data Mapping (Task 15.0). Please coordinate with the tech team.
---FILE_BREAK---
Date: 2026-04-21 10:30 AM | Recipients: Hiroshi Tanaka, David O’Sullivan | Source: Email
From: Hiroshi Tanaka | To: David O’Sullivan | Subject: RE: Nexus Bridge Soils
David, the soil density is more variable than expected. I need to extend the Geotechnical Site Assessment (Task 2.0) to an End Date of May 22, 2026.
---FILE_BREAK---
Date: 2026-10-20 04:22 PM | Recipients: Daniel Kim, Samuel Lee | Source: Email
From: Daniel Kim | To: Samuel Lee | Subject: Hardware Logistics
The edge computing nodes are stuck in customs. Task 19.0 (5G Node Hardware install) is Blocked until further notice.
---FILE_BREAK---
Date: 2026-11-10 08:05 AM | Recipients: David O’Sullivan, Vikram Singh | Source: Email
From: David O’Sullivan | To: Vikram Singh | Subject: Acoustic Barrier Design
Vikram, are you handling the Acoustic Barrier Design (Task 21.0)? I need the specs for the rail link interface.
---FILE_BREAK---
Date: 2027-01-05 09:00 AM | Recipients: Robert Kwok, Samuel Lee | Source: Email
From: Robert Kwok | To: Samuel Lee | Subject: URGENT: Security Protocol
Samuel, we need to add a New Task: "Employee Phishing Simulation" for all staff accessing the 5G Command Centre before Task 25.0 begins.
---FILE_BREAK---
Date: 2026-10-06 11:15 AM | Recipients: Linda Ng, Kevin Zhang, Sarah Chen | Source: Email
From: Linda Ng | To: Kevin Zhang, Sarah Chen | Subject: VDC Coordination
To ensure we don't miss the deadline, both Kevin and Sarah will now be responsible for Task 18.0 (VDC Construction Sequence Simulation).
---FILE_BREAK---
Date: 2026-09-15 03:40 PM | Recipients: Thomas Müller, Sofia Rossi | Source: Email
From: Thomas Müller | To: Sofia Rossi | Subject: ETFE Cushion Delivery
Sofia, the ETFE Cushion System (Task 16.0 related) is on backorder. We are officially Blocked on façade assembly for the atrium.
---FILE_BREAK---
Date: 2026-06-16 01:20 PM | Recipients: Priya Lakshmi, Samuel Lee | Source: Email
From: Priya Lakshmi | To: Samuel Lee | Subject: Task 9.0 Status
Samuel, flooding has damaged the initial irrigation prep. Task 9.0 (Rooftop Garden Design) site prep is Blocked for at least 10 days.
---FILE_BREAK---
Date: 2026-05-12 04:50 PM | Recipients: Amina Al-Farsi, Marcus Wong | Source: Email
From: Amina Al-Farsi | To: Marcus Wong | Subject: URLLC Mapping
Marcus, let’s push the start of Task 5.0 (5G Network Topology) to May 25, 2026, to align with new digital twin sync protocols.
---FILE_BREAK---
Date: 2026-11-03 08:30 AM | Recipients: Vikram Singh, Samuel Lee | Source: Email
From: Vikram Singh | To: Samuel Lee | Subject: Field Report: Task 20.0
Samuel, soil stability issues post-rain mean Task 20.0 (Hydraulic Stormwater) is Blocked. Expecting a 2-week delay in the South Sector.
---FILE_BREAK---
Date: 2026-11-17 10:00 AM | Recipients: Elena Rodriguez, Chloe Dupont | Source: Email
From: Elena Rodriguez | To: Chloe Dupont | Subject: Mandatory Carbon Offset Verification
Chloe, we must add a New Task: "Carbon Offset Verification (Phase A)" before the final Sustainability Audit (Task 22.0).
---FILE_BREAK---
Date: 2026-06-17 09:15 AM | Recipients: Priya Lakshmi, Arjun Mehta | Source: Email
From: Priya Lakshmi | To: Arjun Mehta | Subject: Task 9.0 Status
Arjun, the design phase for the Rooftop Garden (Task 9.0) remains On Track. We are finalizing the irrigation schematics this week.
---FILE_BREAK---
Date: 2027-02-02 02:30 PM | Recipients: Samuel Lee, Geoffery Tan, Jessica Low | Source: Email
From: Samuel Lee | To: Geoffery Tan, Jessica Low | Subject: Claims & Legal Review Oversight
Jessica, I’d like you to take the lead on Task 29.0 (Claims & Legal Liability). Geoffery, please provide her with the files.
---FILE_BREAK---
Date: 2026-09-22 08:00 AM | Recipients: Linda Ng, Sarah Chen | Source: Email
From: Linda Ng | To: Sarah Chen | Subject: RE: MEP Utility Corridor Optimization
Sarah, I need to move the Start Date for Task 17.0 (MEP Corridor Optimization) from September 21 to September 28, 2026.
---FILE_BREAK---
Date: 2026-08-25 11:20 AM | Recipients: Fatima Zahra, Sofia Rossi | Source: Email
From: Fatima Zahra | To: Sofia Rossi | Subject: Task 14.0 Component Issues
Sofia, the smart-grid inverter modules are stuck. Task 14.0 (Smart Grid Integration) is officially Blocked due to supply chain shortages.
---FILE_BREAK---
Date: 2027-01-12 04:00 PM | Recipients: Hassan Meer, Zoe Castellano | Source: Email
From: Hassan Meer | To: Zoe Castellano | Subject: Task 26.0 Progress
Zoe, just confirming the Nightscape Design (Task 26.0) is On Track. Light-spill simulations look excellent.
---FILE_BREAK---
Date: 2026-08-18 08:10 AM | Recipients: Hiroshi Tanaka, Ben Richardson | Source: Email
From: Hiroshi Tanaka | To: Ben Richardson | Subject: Sub-surface Inspection
Ben, we need to add a New Task: "Underwater Drone Piling Inspection" to get clear footage before sign-off on the foundation.
---FILE_BREAK---
Date: 2026-08-04 03:45 PM | Recipients: James Peterson, Samuel Lee | Source: Email
From: James Peterson | To: Samuel Lee | Subject: Emergency Access Protocol
Samuel, the Site Safety Access Protocol (Task 12.0) will be ready "at some point mid-August." Still waiting for the fire marshal.
---FILE_BREAK---
Date: 2026-07-07 05:15 PM | Recipients: Sarah Chen, Marcus Wong | Source: Email
From: Sarah Chen | To: Marcus Wong | Subject: Coordination Timeline
Marcus, due to MEP clashes, the End Date for Task 10.0 (BIM Coordination) has been pushed to October 9, 2026.
---FILE_BREAK---
Date: 2026-12-02 08:30 AM | Recipients: Arjun Mehta, Samuel Lee | Source: Email
From: Arjun Mehta | To: Samuel Lee | Subject: Task 23.0 Monthly Update
Samuel, the Urban Nexus Masterplan Alignment (Task 23.0) is On Track. We are reconciling the bridge with the commercial podium height.
---FILE_BREAK---
Date: 2026-11-10 10:10 AM | Recipients: Isabella Varga, Sofia Rossi | Source: Email
From: Isabella Varga | To: Sofia Rossi | Subject: Acoustic Barrier Lead Times
Sofia, specialized foam for the rail links is unavailable. Task 21.0 (Acoustic Barrier Design) is Blocked regarding material spec.
---FILE_BREAK---
Date: 2026-05-12 11:25 AM | Recipients: Amina Al-Farsi, Robert Kwok | Source: Email
From: Amina Al-Farsi | To: Robert Kwok | Subject: 5G Mesh Reliability
Robert, let’s add a New Task: "5G Mesh Latency Stress Test" for the autonomous shuttles before we finalize Task 5.0.
---FILE_BREAK---
Date: 2026-11-17 03:00 PM | Recipients: Elena Rodriguez, Samuel Lee | Source: Email
From: Elena Rodriguez | To: Samuel Lee | Subject: Task 22.0 Audit
Samuel, we will begin the Sustainability Audit (Task 22.0) "late in the first quarter of next year."
---FILE_BREAK---
Date: 2026-09-08 02:00 PM | Recipients: Alice Thompson, Marcus Wong | Source: Email
From: Alice Thompson | To: Marcus Wong | Subject: Task 15.0 Status
Marcus, the GSIMS Mapping (Task 15.0) is On Track. Satellite imagery for the North Sector has been georeferenced.
---FILE_BREAK---
Date: 2026-08-18 01:15 PM | Recipients: Ben Richardson, Samuel Lee | Source: Email
From: Ben Richardson | To: Samuel Lee | Subject: Task 13.0 Site Issues
Samuel, we’ve found contaminated soil. Task 13.0 (Foundation Piling) is Blocked until the remediation team clears the area.
---FILE_BREAK---
Date: 2026-06-02 11:50 AM | Recipients: David O’Sullivan, Arjun Mehta | Source: Email
From: David O’Sullivan | To: Arjun Mehta | Subject: Public Art Installation
Arjun, we need to include a New Task: "Public Art Installation Structural Review." The sculpture is heavier than initially scoped.
---FILE_BREAK---
Date: 2027-01-19 09:20 AM | Recipients: Omar Bakri, Samuel Lee | Source: Email
From: Omar Bakri | To: Samuel Lee | Subject: Task 27.0 Timeline
Samuel, traffic modeling is taking longer. I need to move the Start Date for Task 27.0 (Transport Flow Simulation) to February 1, 2027.
---FILE_BREAK---
Date: 2027-04-20 08:00 AM | Recipients: Siti Nurhaliza, Samuel Lee | Source: Email
From: Siti Nurhaliza | To: Samuel Lee | Subject: Task 30.0 Readiness
Samuel, everything for the final Archival & Lock (Task 30.0) is On Track. Folders are pre-organized for the April handover.
---FILE_BREAK---
Date: 2027-02-02 04:55 PM | Recipients: Jessica Low, Samuel Lee | Source: Email
From: Jessica Low | To: Samuel Lee | Subject: Task 28.0
Samuel, the Contract Variation (Task 28.0) is On Track. I've incorporated costs for the new drone inspections and carbon verification."""

# Define directory names
meetings_dir = "Meetings_with_metadata_header"
emails_dir = "Emails_with_metadata_header"

# Create directories if they don't exist
os.makedirs(meetings_dir, exist_ok=True)
os.makedirs(emails_dir, exist_ok=True)

# Split the content by the separator
files = raw_content.split("---FILE_BREAK---")

for i, content in enumerate(files):
    # Clean up whitespace and ignore empty splits
    clean_content = content.strip()
    if not clean_content:
        continue
    
    # Remove the section headers if they exist in the chunk
    if "### MEETING SNIPPETS" in clean_content:
        clean_content = clean_content.replace("### MEETING SNIPPETS (Files 001-020)", "").strip()
    if "### EMAIL THREADS" in clean_content:
        clean_content = clean_content.replace("### EMAIL THREADS (Files 021-050)", "").strip()

    # Sort logic: Check if it's a Snippet or an Email thread
    if clean_content.startswith("**Snippet"):
        folder = meetings_dir
        prefix = "Snippet"
    else:
        folder = emails_dir
        prefix = "Email"

    # Generate filename (e.g., Meetings/Snippet_001.txt)
    file_name = os.path.join(folder, f"{prefix}_{i+1:03d}.txt")
    
    with open(file_name, "w", encoding="utf-8") as f:
        f.write(clean_content)
    
    print(f"Created {file_name}")

print("\nSorting complete. Files are organized into /Meetings and /Emails folders.")